### ISSUE TITLE
PHP: composer.phar and composer dependencies should not be part of the repository 

### ISSUE THREAD

**Issue by pendexgabo** [sausheong/polyglot#2]
in the [php responders](https://github.com/sausheong/polyglot/tree/master/responders/php) there is a lot of code that should not be in the repository. This is against the [best practices](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) recommended by the composer project

**Comment by sausheong** [comment]
Good point, thanks for this.

**Comment by sausheong** [comment]
Removed
